In [ ]:
import numpy as np 
import pandas as pd 
import sklearn

In [ ]:
from sklearn.datasets import load_boston
df = load_boston()

In [ ]:
df.keys() # Returns all the keys of the dataset dictionary

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [ ]:
print(df.filename) # Info about the dataset

/usr/local/lib/python3.7/dist-packages/sklearn/datasets/data/boston_house_prices.csv

In [ ]:
boston = pd.DataFrame(df.data, columns=df.feature_names)
boston.head()

      CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [ ]:
boston['MEDV'] = df.target
boston.head()

      CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  MEDV
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [ ]:
boston.isnull()

      CRIM     ZN  INDUS   CHAS    NOX  ...    TAX  PTRATIO      B  LSTAT   MEDV
0    False  False  False  False  False  ...  False    False  False  False  False
1    False  False  False  False  False  ...  False    False  False  False  False
2    False  False  False  False  False  ...  False    False  False  False  False
3    False  False  False  False  False  ...  False    False  False  False  False
4    False  False  False  False  False  ...  False    False  False  False  False
..     ...    ...    ...    ...    ...  ...    ...      ...    ...    ...    ...
501  False  False  False  False  False  ...  False    False  False  False  False
502  False  False  False  False  False  ...  False    False  False  False  False
503  False  False  False  False  False  ...  False    False  False  False  False
504  False  False  False  False  False  ...  False    False  False  False  False
505  False  False  False  False  False  ...  False    False  False  False  False

[506 rows x 14 columns]

In [ ]:
boston.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
 
X=boston.drop('MEDV', axis=1)
Y=boston['MEDV']
 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.15, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(430, 13)
(76, 13)
(430,)
(76,)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [ ]:
## FITTING MODEL ON THE TRAINING DATASET
 
lin_model = LinearRegression()
lin_model.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_train_predict = lin_model.predict(X_train)
rmse = (np.sqrt(mean_squared_error(Y_train, y_train_predict)))
 
print("The model performance for training set")
print('RMSE is {}'.format(rmse))
print("\n")
 
# on testing set
y_test_predict = lin_model.predict(X_test)
rmse = (np.sqrt(mean_squared_error(Y_test, y_test_predict)))
 
print("The model performance for testing set")
print('RMSE is {}'.format(rmse))

The model performance for training set
RMSE is 4.710901797319796


The model performance for testing set
RMSE is 4.687543527902972